### ISSUE TITLE
Upgrade normalize-url

### ISSUE THREAD

**Issue by boostpaal** [lukechilds/cacheable-request#103]
Please upgrade normalize-url, because of known vulnerabilities:
https://app.snyk.io/vuln/SNYK-JS-NORMALIZEURL-1296539

**Comment by tomgrossman** [comment]
yep...
https://app.snyk.io/vuln/SNYK-JS-NORMALIZEURL-1296539

**Comment by christian-hawk** [comment]
Yes, normalize url < 6.x provides **HIGH SEVERITY** vulnerability.
