### ISSUE TITLE
Shared or private cache

### ISSUE THREAD

**Issue by mokkabonna** [lukechilds/cacheable-request#23]
Is this library meant as a private or a shared cache?

If shared, is there a straight forward way to be using this library in cooperation with a shared cache like a reverse proxy?
https://github.com/nodejitsu/node-http-proxy

**Comment by lukechilds** [comment]
It is suitable to be used a shared cache, `private` is not cacheable and `s-maxage` is respected.

I don't think nodejitsu/node-http-proxy supports passing in a request function so not with that lib directly but I'm sure there are others that do. If not it wouldn't be too simple to write your own, for example see:

https://github.com/lukechilds/pirateproxy (Got uses `cacheable-request` under the hood)

**Comment by lukechilds** [comment]
I have actually been meaning to build a reverse proxy backed by `cacheable-request` but haven't had the time to put into it yet.

Let me know if you build it, I'd love to link to it in the readme.

**Comment by mokkabonna** [comment]
My understanding is that there are two types of cache, shared and private (called user agent cache or single user cache)

https://github.com/kornelski/http-cache-semantics#constructor-options 

> If options.shared is true (default), then the response is evaluated from a perspective of a shared cache (i.e. private is not cacheable and s-maxage is respected). If options.shared is false, then the response is evaluated from a perspective of a single-user cache (i.e. private is cacheable and s-maxage is ignored).


And MDN:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Cacheability

> private
>  Indicates that the response is intended for a single user and must not be stored by a shared cache. A private cache may store the response.

Anyway by diving into this library code, I can see that it is using the default options of http-cache-semantics  which has shared cache set to true. So it will not cache any response that have `cache-control: private`

It would be nice if we could set all or some of the cachepolicy options ourselves. I am implementing a user agent and would benefit from caching responses with `cache-control: private`

**Comment by lukechilds** [comment]
Sorry, just seen this, yeah definitely, it should be very simple to change.

For example:

```js
response.cachePolicy = new CachePolicy(opts, response);
```

Just needs to be:

```js
response.cachePolicy = new CachePolicy(opts, response, opts.cachePolicy);
```

(or similar)

And then you have full control over the `CachePolicy` options.
