### ISSUE TITLE
Pass options to underlying http-cache-semantics

### ISSUE THREAD

**Issue by kirillgroshkov** [lukechilds/cacheable-request#32]
I'm trying to use `got` to cache my authenticated github requests.

Github API returns `Cache-Control: private` header for authenticated requests, so `http-cache-semantics` without `shared: false` option determines the response as not cacheable.

I'd like to find a way to pass `shared: false` configuration all the way `got > cacheable-request > http-cache-semantics`. Any ideas how?

UPD: By reading source code in all 3 libraries I figured that I can just pass `shared: false` in got options (despite typescript forbidding it) and it goes all the way to `http-cache-semantics`. But unfortunately it doesn't solve my problem of authenticated github requests being not cached. Digging further...

**Comment by lukechilds** [comment]
Closed as https://github.com/sindresorhus/got/issues/480 is closed.
