### ISSUE TITLE
Cache never overwrites with fresh data

### ISSUE THREAD

**Issue by dimitridaras** [lukechilds/cacheable-request#36]
Hi. It appears that cached data is being returned even when the cache expires.

The client calls call to a server endpoint (via cacheable-request) which returns a response with Cache-Control: public, max-age=300. When the client makes the same request again, I can see that the server endpoint is only being hit once every five minutes, as expected. I can also see that the response from the server is a 200 with new data and the same Cache-Control header. However, this new data is not returned from cacheable-request. The previously cached version is returned.

I've recently been trying this with the npm "got" package, but I saw the same behaviour using cacheable-request.

Note that I am not setting the strictTtl option.

Is this user error?!

**Comment by adityapatadia** [comment]
Does the server return any Etag or last-modified headers?

**Comment by adityapatadia** [comment]
Let us know if you still face the issue after trying above. We will re-open it.

**Comment by dimitridaras** [comment]
The server does not return LastModified or Etags. Surely if the server does not return a 304, then the old response should be considered stale and replaced with the new response?

**Comment by adityapatadia** [comment]
We will get it checked. It's always good practice to return Etag or LastModified if you control the server.
