### ISSUE TITLE
Should we migrate to Jest as testing framework?

### ISSUE THREAD

**Issue by adityapatadia** [lukechilds/cacheable-request#70]
I am thinking to migrate this library to test with https://jestjs.io/. In my personal experience it's faster, nicely maintained (by facebook) and more feature rich. Ava has many problems like if you try to run tests for v6.0 on Node 10, the process gets stuck without any explanations.

Let me know your thoughts.

**Comment by lukechilds** [comment]
I really enjoy working with AVA and use it for all my projects. I'm very familiar with it so for me personally, I see no reason to change.

I haven't encountered any perf or stability issues with AVA, but if we were having specific issues with AVA that were solved with Jest then I would be open to migrating.

But currently, this seems like more of a personal preference than a technical issue. Everyone loves their own testing framework and hates all the others 😉

**Comment by adityapatadia** [comment]
I am not sure if it's just me but I find lot of issues with AVA. For example, when I run the tests for nodejs v10, it just hangs without any explanation. I will try to fix it first but when I moved from mocha/chai to Jest, I found it wayyy better for my personal projects. That feel is not there with Ava but let's see. If we can fix it, I am not in hurry to migrate to Jest.

**Comment by adityapatadia** [comment]
Closing this as test framework is now working. May be it was my inexperience with Ava that prompted me to say above. I will re-open in future if this is desired.
