### ISSUE TITLE
RequestError: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by manusis** [lukechilds/cacheable-request#84]
Getting the following error when trying to use https request

unhandledRejection { RequestError: Protocol "https:" not supported. Expected "http:"
    at /Users/rajiv/myprojects/crawler-server/node_modules/cacheable-request/src/index.js:200:23

**Comment by lukechilds** [comment]
Did you pass in `https.request` as the request function?

**Comment by manusis** [comment]
Hi Luke,  yes I noticed it later. Working with https.request. Thanks.
